build:
  verbosity: detailed

build_script:
  - .ci/appveyor.bat

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk11
  - JAVA_HOME: C:\Program Files\Java\jdk12
